//NO UTILIZADO......
//INICIALMENTE SE IBA A USAR PARA GRABAR LOS DATOS EN FORMATO JSON...
var json = $.getJSON({'url': 'precios.json', 'async': false});
var precios = JSON.parse(json.responseText);
